#!/usr/bin/perl

########################################################
my $PKGDIR          = $ARGV[0];
my $TARGET          = $ARGV[2];

## Run postflight makeuser and/or kickstart events, if any
system("$PKGDIR/Contents/Resources/postflight_kickstart", "$TARGET");

exit(0);
